--- # Uninstallig Nginx
- hosts: nginx_server
  user: ubuntu
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:

    - name: stopping nginx
      service:
        name: nginx
        state: stopped  

    - name: "Uninstall NginX"
      apt:
        name: nginx-common
        state: absent
        autoremove: yes