--- # Installing Nginx
- hosts: nginx_server
  user: ubuntu
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:
    - name: Installing Nginx
      apt:  
        name: nginx
        state: present